### ISSUE TITLE
Suggestion: Mobs that immune/weak to certain weapons + weapon mods suggestion

### ISSUE THREAD

**Issue by Norinoku** [Eclipse-Ilx/Abyssal-Descent#10]
To improve pack's progression and make layers more difficult the deeper you go, you can add immunity/weakness to certain damage types for mobs and add more weapons with special abilities to make gameplay more interesting.

Example: Mobs that can only be killed with two-handed weapon. That way the player won't be able to use shield, making the fight harder. Or the mob that is significantly weaker to fire spells. Or the mob that can only be killed with explosives (whether that would be Galosphere's bombs or Iron's Spells 'n Spellbooks's explosive spells). That way the player won't stick with a single weapon/spell type until the end. Just make sure to not give every single mob a different immunity, I would choose like 2-3 weapon types for a layer, so that then the player would have to change the weapon type on the next layer.

Mod to diversify the weapon pool:

### **Simply Swords**
Adds a lot of different weapons, including mentioned earlier two-handed weapons, weapons with special effects and others. For example: Spears, Glaives, Chakrams, Katanas, Greathammer/axes, Rapiers and more. 
https://www.curseforge.com/minecraft/mc-mods/simply-swords

### **Iron's Spells 'n Spellbooks**
Adds tons of vanilla+ spells, offensive and defensive. Spells can be found or crafted with ink, both can be found in the chests. Just make sure to gatekeep some of the spells crafts and spawns behind progression. This would greatly improve and diversify the gameplay.
The mod also adds some dungeons and bosses, so you can add them on layers too
https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

### **Better Combat**
A simple mod to make Simply Swords' and vanilla weapons' animations look better, highly recommend
https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus

### **Relics**
Also a cool mod I found.
Mod that adds upgradable (with usage) relics with various effects, for example turning enemy's healing against themselves. time rewinder, portal that can teleport mobs, and maaany more. Gives Made in Abyss vibes, which the pack takes inspiration from.
https://www.curseforge.com/minecraft/mc-mods/relics-mod

I think all these mods would help rewarding the player for defeating certain dungeons/bosses
You should also change most of those items' spawn based on layers for better progression. Also some of the weapons/spells are pretty strong so I recommend balancing it too, increasing the hp of mobs (or simply banning them...)

**Comment by Eclipse-Ilx** [comment]
These ideas are cool but I don't think they fit with the vision we have for this modpack, I have used a lot of these mods in the past and they are good mods tho. I will keep this suggestion in mind if anything changes as we work on the pack.
