### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by Potang0** [Eclipse-Ilx/Abyssal-Descent#12]
I think that this modpack really needs a biome mod such as Biomes O' Plenty to liven up the overworld. It would provide players with an incentive to explore the overworld for longer instead of immediately getting the required tools to dig to other layers. Also, with the other dimensions having many different biomes and places to explore I think it is only fair to boost the energy of the overworld. When compared to with dimensions like the end(with better_end) and the Undergarden, the overworld is bland and routine. To me the overworld is the same old thing every time and this mod makes it exciting and fresh, and also fits the theme of the modpack wonderfully. I wouldn't consider it high on priority but just putting it out there as an option.

**Comment by Eclipse-Ilx** [comment]
We probably will not add Biomes O' Plenty but we will be adding some overworld generation mods to spice things up yeah... originally we weren't going to due to some limitations but now we can so soonTM
