### ISSUE TITLE
gradle wrapper is missing

### ISSUE THREAD

**Issue by skrybl** [Eclipse-Ilx/Abyssal-Descent#14]
its just gone, you cant use make because it throws an error
(*.jar in the gitignore means that the gradle wrapper is likely also, being ignored)

**Comment by Eclipse-Ilx** [comment]
This should be fixed soon? @slbsh

**Comment by slbsh** [comment]
Accidentally closed lol (still getttin used to the whole closin through commits thing). 
Can you check if the issue persists?
