### ISSUE TITLE
Wrong modpack.

### ISSUE THREAD

**Issue by ghost** [Eclipse-Ilx/Abyssal-Descent#2]
Im a huge buffoon and im very sorry. Found out about the modpack. Was linked to your discord. And the video (was either a short or tiktok i found, linked to a completely different modpack.

**Comment by slbsh** [comment]
Could you try to reproduce the bug and provide a minimal reproducable example?

**Comment by ghost** [comment]
I get a backpack, Dig past into the Abyss layer 1 from the overworld. Backpacks are no longer usable at all. I go back into the overworld, still not usable. Only when I kill myself am I able to use my bag again.
Though I cant seem to reproduce the bag disappearing part.
[Video here](https://www.dropbox.com/scl/fi/hdblep1yqwybne4z8hech/Minecraft-Forge_-1.20.1-2024-09-24-13-29-45.mp4?rlkey=pfzzg0e1ld94eo5xtfjw9kxka&st=cppvr5j6&dl=0)
if you see me stopping i'm tapping the key to open the backpack.

Edit: The only work around I know of currently, is to just keep the backpack **IN your inventory** and use it from there. But if its on your back, it fully breaks.

**Comment by slbsh** [comment]
@Aimsell something for you :p

**Comment by Eclipse-Ilx** [comment]
The video shown is from the Eternal Descent modpack, we are developing a separate modpack called Abyssal Descent.
