### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by Danmatisk-Yellow** [Eclipse-Ilx/Abyssal-Descent#5]
### Mobility:

In a pack as vertical as this players will need tools for mobility. The grappling hook is a good start but won't fill that need enough imo.
**Wall jump** - A basic tool that's built in to the player that allows them to climb smaller gaps and slide down walls, something that players will run into constantly inside the huge caves and become a frequent annoyance. This mod also offers a double jump that can be locked behind an enchantment, which can be loot only in a specific structure somewhere in a deep layer, so it can be like a late-game mobility tool for players to earn.
https://modrinth.com/mod/wall-jump-txf
**Paragliders** - This is useful as a safe slow falling tool for safely descending down caves. This mod is based on the botw paraglider, so the glider is balanced out by a stamina meter limiting how long you can use it. The meter can be increased with spirit orbs, which are perfect for having as loot in underground structures so the player's stamina can slowly increase the more they progress through the pack. The mod also lets you increase your base health with spirit orbs but that can be disabled.
https://www.curseforge.com/minecraft/mc-mods/paragliders

### Worldgen:

Plenty of layers sorely need more content to flesh them out. The mods' contents recommended below can be features scattered throughout the default layers, localized within structures, or fill entirely new biomes. 

**Alex caves** - tons of fleshed out content that are already well designed for caves, and some cave themes match well with some layers.
Abyssal chasm (underwater cave) assets -> challenger deep
Magnetic caves -> delvers beginnings (to match the crystal theme)
Forlorn hollows (cult cave) -> final maelstrom
Toxic caves -> final maelstrom
Primordial caves -> maybe fight dinosaurs inside amber structures, common hollow earth trope
https://www.curseforge.com/minecraft/mc-mods/alexs-caves

**Spelunkery** - general mining revamp mod, adds plenty of useful tools and some interesting cave features
Most features -> overworld and delvers beginnings
The mushrooms and fungi -> blighted bogs
https://www.curseforge.com/minecraft/mc-mods/spelunkery

**Galosphere** - Same as spelunkery
Crystal canyons -> delvers beginnings
Lichen caves -> blighted bogs
https://www.curseforge.com/minecraft/mc-mods/galosphere

**Aquamirae** - A frozen ocean themed mod that would fit pretty well in the ice caves. It has its own progression which would work decently well inserted into the pack's grand progression. 
Everything over the water -> frozen waste
Everything inside the water -> challenger deep
https://www.curseforge.com/minecraft/mc-mods/ob-aquamirae

### General:

**Quark** - just a good all use mod that good to have in any pack. Especially adds some useful features for the nether and end. And some assets good for dungeon designing. 
https://www.curseforge.com/minecraft/mc-mods/quark

**Target dummy** - there's tons of weapons in this pack already and I despise not being able to know how powerful they are from eachother (raw stats usually aren't enough when tools have more mechanics)
https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm

**Hardcore questing mode** - this is a controversial addition but it doesn't have to be implemented too heavily. There can just be a single quest for each layer that guides the player on how to progress correctly, along with a few subquests per layer that encourage the player to explore and utilize the features of each layer. I also like the idea of using the limited lives feature on this pack, but it can be optional. 
https://www.curseforge.com/minecraft/mc-mods/hardcore-questing-mode

The ender dragon is definitely gonna need a heavy overhaul to mix things up as well as have a more fitting difficulty. This will probably take new mods created for this pack to pull off, but here's two that can work as a springboard:
https://www.curseforge.com/minecraft/mc-mods/ender-trigon
https://modrinth.com/datapack/true-ending

**Comment by slbsh** [comment]
adding quark.

@Eclipse-Ilx have a peek at **Alex's Caves**, **Spelunkery**, and **Galosphere**

**Comment by slbsh** [comment]
We're gonna add `Alex's Caves`, `Galosphere` and `Spelunkery` as well in the future. Thanks for the suggestions!
