### ISSUE TITLE
Ore generation funky

### ISSUE THREAD

**Issue by Potang0** [Eclipse-Ilx/Abyssal-Descent#8]
Crash logs with backtraces: N/A

Info about your machine: 32 Gb ram and 1 TB of storage. Intel core i7 CPU 2.20 GHz

Version: Minecraft 1.20.1 on Forge 47.3.10  [release.txt](https://github.com/user-attachments/files/17158655/release.txt)

Minimal reproducible example: check ore generation between the same seed in unmodded and modded minecraft.

Screenshots/detailed descriptions: In Abyssal Descent seeds I have not been able to find any diamonds at all in the overworld, even in its y-level hotspots. Moreover, I could find little to no iron in "normal" y-levels for iron to spawn, even in mountain biomes there were none. Not until I went to y-level -15 in deepslate level did I find any iron. It didnt just start appearing either, once I got to that -15 y level it was everywhere. See added pictures of unmodded and then the modded version of the SAME seed and SAME place.
![2024-09-26_23 03 20](https://github.com/user-attachments/assets/90cbde48-7781-4738-a9d5-68bd755f3e9c)
![2024-09-26_23 14 25](https://github.com/user-attachments/assets/b9e37f86-dbde-4430-a50d-f9da41ebaed3)

**Comment by slbsh** [comment]
This is intentional design.

Diamonds will not be found in the overworld and you'll have to go to layer 1 to get em,
while iron is only gonna generate in deepslate and will require a copper pickaxe to mine.
